name: ğŸš€ Production deployment
# Only trigger, when the build workflow succeeded
on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: photoscavenger
jobs:
          
  buildingimage:
    name: ğŸš€ Launching new version...
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‚  Getting all the code Peter has written
        uses: actions/checkout@v2
      - name: âš™ï¸  Updating to the latest versions
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: ğŸ¢ Install Amazon Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: ğŸ¤ Log in to AWS Lightsail with Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: ğŸ¤– Downloading Machine Learning Model (Yolov5X)
        run: wget https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5m.pt
      - name: ğŸ“Š Downloading the usage stats from the current server to the new server for continuity
        run: curl -X GET "https://photoscavenger.vdotvo9a4e2a6.eu-central-1.cs.amazonlightsail.com/get_long_term_data" > statslongterm.json
        
      - name: ğŸ³ Create a Docker Container
        run: docker build -t photoscavenger:latest .
      - name: ğŸ“¬ Upload container image to AWS container register
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${service_name} \
            --image ${service_name}:latest

      - name: ğŸš€ Deploying the container to the Amazon datacenter
        run: |
          aws lightsail create-container-service-deployment --service-name photoscavenger \
            --containers file://AWS/deploymentconfig.json \
            --public-endpoint file://AWS/publicendpoint.json
      - name: =========== All done. Cleaning up â™»ï¸  ===========
        run: ls
